version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 52181:2181
    networks:
      - infrastructure_fawry-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka:9092,INTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - infrastructure_fawry-network

  redis:
    image: redis:latest
    container_name: fawry_cache
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - infrastructure_fawry-network
    restart: unless-stopped

  postgres:
    image: postgres:15-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - infrastructure_fawry-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  infrastructure_fawry-network:
    driver: bridge

volumes:
  postgres_data:
