version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: fawry_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - infrastructure_fawry-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: fawry_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - infrastructure_fawry-network


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - infrastructure_fawry-network


  redis:
    image: redis:latest
    container_name: fawry_cache
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - infrastructure_fawry-network
    restart: unless-stopped

  postgres:
    image: postgres:15-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - infrastructure_fawry-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  infrastructure_fawry-network:
    driver: bridge

volumes:
  postgres_data: